services:
  app:
    build: ./app
    container_name: airport_app
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TOKEN_EXPIRE_MINUTES: 60
  
  database:
    image: postgres:latest
    container_name: airport_database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: airport_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  data:
  redis_data: