CREATE ROLE reader WITH LOGIN PASSWORD '12345678';

GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO reader;

CREATE ROLE super WITH LOGIN PASSWORD '12345678' SUPERUSER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO super;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO super;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO super;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO super;

CREATE USER reader1 WITH PASSWORD '12345678';
GRANT reader TO reader1;

--CREATE USER super1 WITH PASSWORD '12345678';
GRANT super TO super1;